module.exports = {
  "general": {
    "dark": true
  },
  "q-app":{
    "style": ""
  },
  "q-logo":{
    "style": "display: none"
  },
  "q-content":{
    "style": ""
  },
  "q-container":{
    "style": "padding: 0 10px;"
  },
  "q-navigation-drawer":{
    "app":false,
    "dark":true,
    "right":true,
    "clipped":true,
    "fixed":true,
    "miniVariant":false,
    "expandOnHover":false,
    "temporary":true,
    "floating":false,
    "permanent":false,
    "width":"1200"
  },
  "q-btn":{
    "hideIcon":true,
    "hideText":false,
    "minWidth":20,
    "minHeight":20,
    "maxWidth":300,
    "maxHeight":300,
    "elevation":0,
    "block":false,
    "fab":false,
    "outlined":false,
    "rounded":false,
    "text":false,
    "tile":true,
    "x-small":false,
    "small":false,
    "medium":true,
    "large":false,
    "x-large":false,
    "class": "mx-2"
  },
  "q-btn-input":{
    "hideIcon":false,
    "hideText":true,
    "minWidth":"28",
    "minHeight":"28",
    "maxWidth":"28",
    "maxHeight":"28",
    "elevation":0,
    "block":false,
    "fab":false,
    "outlined":false,
    "rounded":false,
    "text":true,
    "tile":true,
    "x-small":false,
    "small":true,
    "medium":false,
    "large":false,
    "x-large":false,
    "class": "mx-2"
  },
  "q-tabs":{
    "icons":false,
    "elevation":0,
    "color":"#EF6C00",
    "backgroundColor":"#FFFFFF00",
    "dark":true,
    "centered":false,
    "grow":false,
    "vertical":true,
    "right":false
  },
  "q-btn-table":{
    "hideIcon":false,
    "hideText":true,
    "minWidth":"28",
    "minHeight":"28",
    "maxWidth":"28",
    "maxHeight":"28",
    "elevation":0,
    "block":false,
    "fab":false,
    "outlined":false,
    "rounded":false,
    "text":true,
    "tile":true,
    "x-small":false,
    "small":true,
    "medium":false,
    "large":false,
    "x-large":false,
    "class": "mx-2"
  },
  "colors":{
    "background":"#292929",
    "header":"#212121",
    "primary":"#EF6C00",
    "secondary":"#424242",
    "accent":"#F44336",
    "error":"#FF5252",
    "info":"#2196F3",
    "success":"#4CAF50",
    "warning":"#FFC107"
  },
  "q-snackbar":{
    "timeout":6000,
    "left":null,
    "top":null,
    "bottom":true,
    "multi-line":false,
    "vertical":false,
    "right":null
  },
  "q-app-bar":{
    "absolute":false,
    "fixed":false,
    "dark":true,
    "extended":false,
    "dense":false,
    "elevation":0,
    "color":"#212121"
  },
  "q-sidebar":{
    "color":"#212121",
    "stateless":false,
    "dark":true,
    "right":false,
    "clipped":false,
    "fixed":true,
    "miniVariant":false,
    "expandOnHover":false,
    "temporary":false,
    "floating":false,
    "permanent":false,
    "app":true,
    "width":"250"
  },
  "q-dialog":{
    "hideOverlay":false,
    "maxWidth":1200,
    "scrollable":false,
    "fullscreen":null,
    "transition":"dialog-bottom-transition"
  },
  "q-form":{
    "type":"q-navigation-drawer"
  },
  "q-card":{
    "color":"#424242",
    "outlined":false,
    "elevation":1,
    "tile":true,
    "dark":true,
    "borderSize":0,
    "borderColor":"#424242FF"
  },
  "q-autocomplete":{
    "shaped":false,
    "outlined":false,
    "rounded":false,
    "solo":false,
    "singleLine":false,
    "filled":false,
    "persistentHint":false,
    "flat":false,
    "color":"#FFFFFF00",
    "backgroundColor":"#FFFFFF00"
  },
  "q-select":{
    "shaped":false,
    "outlined":false,
    "rounded":false,
    "solo":false,
    "singleLine":false,
    "filled":false,
    "persistentHint":false,
    "flat":false,
    "color":"#FFFFFF00",
    "backgroundColor":"#FFFFFF00"
  },
  "q-textarea":{
    "autoGrow":false,
    "autofocus":true,
    "clearable":false,
    "counter":0,
    "filled":false,
    "flat":false,
    "noResize":false,
    "outlined":false,
    "persistentHint":false,
    "placeholder":null,
    "rounded":false,
    "rowHeight":24,
    "rows":1,
    "shaped":false,
    "singleLine":false,
    "solo":false,
    "color":"#FFFFFF00",
    "backgroundColor":"#FFFFFF00"
  },
  "q-text-field":{
    "shaped":false,
    "outlined":false,
    "rounded":false,
    "solo":false,
    "singleLine":false,
    "filled":false,
    "persistentHint":false,
    "flat":false,
    "color":"#FFFFFF00",
    "backgroundColor":"#9C27B0FF"
  },
  "q-icon":{
    "color":"#E0E0E0",
    "backgroundColor":"#ffffff00"
  }
}