module.exports = {
  "general": {
    "dark": false
  },
  "q-app":{
    "style": ""
  },
  "q-logo":{
    "style": "display: none"
  },
  "q-content":{
    "style": ""
  },
  "q-container":{
    "class": "px-5",
  },
  "q-navigation-drawer":{
    "color":"#ffffff",
    "app":false,
    "dark":false,
    "right":true,
    "clipped":false,
    "fixed":true,
    "miniVariant":false,
    "expandOnHover":false,
    "temporary":true,
    "floating":false,
    "permanent":false,
    "width":"1200"
  },
  "q-btn":{
    "hideIcon":true,
    "hideText":false,
    "minWidth":20,
    "minHeight":20,
    "maxWidth":300,
    "maxHeight":300,
    "elevation":0,
    "tile":true,
    "medium":true,
    "class": "mx-2"
  },
  "q-btn-input":{
    "hideIcon":false,
    "hideText":true,
    "minWidth":"28",
    "minHeight":"28",
    "maxWidth":"28",
    "maxHeight":"28",
    "elevation":0,
    "text":true,
    "tile":true,
    "small":true,
    "class": "mx-2"
  },
  "q-btn-table":{
    "hideIcon":false,
    "hideText":true,
    "minWidth":"28",
    "minHeight":"28",
    "maxWidth":"28",
    "maxHeight":"28",
    "elevation":0,
    "text":true,
    "tile":true,
    "small":true,
    "class": "mx-2"
  },
  "q-tabs":{
    "icons":false,
    "vertical":true,
    "elevation":0,
    "color":"#1976d2",
    "backgroundColor":"#FFFFFF00",
  },
  "colors":{
    "background":"#fafbff",
    "header":"#FFFFFF",
    "primary":"#1976D2",
    "secondary":"#424242",
    "accent":"#82B1FF",
    "error":"#FF5252",
    "info":"#2196F3",
    "success":"#4CAF50",
    "warning":"#FFC107"
  },
  "q-snackbar":{
    "timeout":6000,
    "bottom":true,
  },
  "q-app-bar":{
    "fixed":true,
    "elevation":0,
    "color":"#fff"
  },
  "q-sidebar":{
    "color":"#ffffff",
    "fixed":true,
    "app":true,
    "width":"250"
  },
  "q-dialog":{
    "maxWidth":1200,
    "fullscreen":null,
    "transition":"dialog-bottom-transition"
  },
  "q-form":{
    "type":"q-navigation-drawer"
  },
  "q-card":{
    "color":"#ffffff",
    "outlined":true,
    "elevation":0,
    "tile":true,
    "dark":false,
    "borderSize":2,
    "borderColor":"#F1F1F1FF"
  },
  "q-autocomplete":{
  },
  "q-select":{
  },
  "q-textarea":{
    "autoGrow":false,
    "autofocus":true,
    "rowHeight":24,
    "rows":1,
  },
  "q-text-field":{
  }
}